version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_meeting_room
    environment:
      POSTGRES_DB: meeting_room
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: whyear4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: